# TensorFlow 기초

* Tensorflow는 Tensor의 흐름을 이야기 한다.
* tensor가 한연산에서 다른 연산으로 흐르는 것을 이야기 한다.
* 아래의 코드들은 이러한 tensor를 만들고 다루는 법에 대해 나와있다.



# tf.constant

* tf.constant로 행렬을 만들 수 있다.
* 아래의 경우 2행 3열의 행렬이 만들어진다.
* numpy 행렬과 비슷하게 tf.Tensor는 크기 (shape)과 데이터타입 (dtype)을 가진다.
* 아래의 코드를 확인하면 그에 대한 내용을 확인 할 수 있다.

In [1]:
import tensorflow as tf

In [5]:
tf.constant([[1,2,3],[4,5,6]])

#tf.constant(10)
#행렬이 아닌 스칼라 값도 생성가능

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [7]:
p = tf.constant([[1,2,3],[4,5,6]])
p.shape

TensorShape([2, 3])

In [8]:
p.dtype

tf.int32

# 인덱스 참조

* 아래의 코드를 통해서 확인하면 인덱스를 참조하는 방식도 numpy와 유사한것을 알 수 있다.

In [9]:
p[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [10]:
p[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

# 텐서 연산

* p + 10의 경우 행렬값 모두에 10이 더해지는 것을 확인할 수 있다.
* tf.square를 통해 확인한 경우 제곱값으로 행렬값이 바뀌는 것을 확인할 수 있다.
* p + 10의 경우 tf.add(p,10)과 같은 경우고 이를 호출하는 것과 같다.
* @ 연산은 행렬곱을 위한 연산으로 tf.matmul() 함수 호출과 같다.
* 텐서플로우의 경우 transpose는 전치된 행렬의 복사본으로 새로운 tensor가 만들어진다.

# 텐서플로우 기본 수학 연산

* tf.add()
* tf.multiply()
* tf.square()
* tf.exp()
* tf.sqrt()
* tf.reshape() [넘파이와 유사]
* tf.squeeze() [넘파이와 유사]
* tf.title() [넘파이와 유사]

# 넘파이와 겹치지만 이름이 다른 함수들

* tf.reduce_mean() = np.mean() 
* tf.reduce_sum() = np.sum()
* tf.reduce_max() = np.max()
* tf.math.log() = np.log()



In [11]:
p + 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [13]:
tf.square(p)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [16]:
p @ tf.transpose(p)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

# keras의 저수준 API

* square() / exp() / sqrt() 등등
* keras.backend에 keras의 저수준 API가 들어있다.
* 아래는 keras의 저수준 API인 keras.backend의 사용 예시다.

In [17]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(p)) + 9

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 25],
       [13, 34],
       [18, 45]], dtype=int32)>

# 넘파이와 텐서플로우

* 텐서플로우와 넘파이는 같이 사용하기 좋다.
* 텐서를 넘파이 배열로 , 넘파이 배열을 텐서로 바꾸는 과정이 어렵지 않기 때문이다.
* 따라서 넘파이 연산이나 텐서플로우 연산을 모두 사용할 수 있다는 것이다.

In [18]:
import numpy as np
a = np.array([2,4,5])
tf.constant(a)
#constant()를 통해 넘파이 배열을 텐서로 변환

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 4, 5])>

In [19]:
p.numpy()
#numpy()를 통해 텐서를 넘파이 배열로 변환

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [20]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 4, 16, 25])>

In [21]:
np.square(p)

#위의 두 코드처럼 넘파이 , 텐서플로우 연산을 자유자재로 사용 가능하다.


#넘파이는 64비트 정밀도 / 텐서플로우는 32비트 정밀도
#넘파이 배열로 텐서를 만들때는 dtype = tf.float32 여야 한다.

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

# 타입 변환

* 다른 타입끼리의 연산시 타입이 자동으로 변환될 수 있다.
* 이는 사용자에게 혼동을 유발하고 잘못된 결과가 나오게 할 수 있다.
* 따라서 텐서플로우는 이러한 자동 타입 변환을 막고 있다.
* 예를 들어 정수 tensor와 실수 tensor는 서로 더할 수 없다.
* ex) tf.constant(2) + tf.constant(5.1) => error
* 타입변환이 필요한 경우 tf.cast() 함수를 통해 구현 가능하다.

In [25]:
pp = tf.constant(5.1, dtype=tf.float64)
tf.constant(2.1) + tf.cast(pp, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=7.2>

# 변수

* tf.Tensor는 constant 즉 상수 , 변경되지 않는다.
* tensor의 내용을 바꾸기 위해선 상수가 아닌 변수로 만들어야 한다.
* tf.Variable로 이를 만들 수 있다.
* 즉 tf.constant는 상수 tensor , tf.Variable은 변수 tensor를 만든다.

# tf.Variable

* tf.Variable 역시 constant와 비슷하게 넘파이와 호환된다.
* 또한 데이터 타입 역시 마찬가지다.
* 내부의 값을 바꾸고 싶으면 assign() 메소드를 사용하면 된다.
* assign_add() / assign_sub() 등을 통해 더하고 뺄 수도 있다.
* 원소에 assign() 메소드 혹은 scatter_update() , scatter_nd_update()를 통해 개별원소나 슬라이스를 수정 할 수도 있다.

In [26]:
o = tf.Variable([[1,2,3],[4,5,6]])
o

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [27]:
o.assign(3*o)
#o 행렬에 곱하기 3

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 3,  6,  9],
       [12, 15, 18]], dtype=int32)>

In [28]:
o[0,1].assign(77)
#행렬값 변경

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 3, 77,  9],
       [12, 15, 18]], dtype=int32)>

In [29]:
o[:,2].assign([99,999])
#슬라이스로 행렬값 변경

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[  3,  77,  99],
       [ 12,  15, 999]], dtype=int32)>

In [30]:
o.scatter_nd_update(indices=[[0,0],[1,2]], updates=[100,200])
#[0,0] 과 [1,2]의 행렬값을 updates 뒤쪽의 값으로 업데이트함

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100,  77,  99],
       [ 12,  15, 200]], dtype=int32)>

# 텐서플로우의 다양한 데이터 구조

### 희소 텐서 (tf.SparseTensor)

* sparse한 텐서, tf.sparse 패키지는 희소 텐서를 위한 연산을 제공함

### 텐서 배열 (tf.TensorArray)

* 텐서의 리스트다.
* 기본적으로는 고정된 길이 하지만 동적으로 바꿀 수 있음
* 리스트에 포함된 모든 텐서는 크기 , 데이터 타입이 동일해야함

### 래그드 텐서 (tf.RaggedTensor)

* 래그드 텐서는 리스트의 리스트다.
* 텐서에 포함된 값은 동일한 데이터 타입 하지만 리스트의 길이는 다를 수 있음
* tf,ragged 패키지에서 래그드 텐서를 위한 연산을 제공함

### 문자열 텐서 (tf.string)

* 유니코드가 아닌 바이트 문자열
* tf.strings 패키지에서 유니코드 문자열과 이러한 텐서 사이의 변환 연산을 제공함
* tf.string은 기본 데이터 타입이라 문자열의 길이가 텐서 크기에 나타나지 않음
* 유니코드 텐서로 바꾸면 문자열 길이가 텐서 크기에 표현됨

### 집합 (set)

* 일반적으로 집합은 텐서 마지막 축의 벡터에 의해 표현된다
* tf.sets 패키지에서 집합과 관련된 연산들을 제공함

### 큐 (queue)

* 큐는 단계별로 텐서를 저장함
* 우선순위 큐 / 선입선출 큐 / 패딩 배치 큐 / 원소셔플 큐 등 다양한 큐 구조를 제공한다.
* 위의 이러한 클래스들은 tf.queue 패키지에 포함되어 있다.